### ISSUE TITLE
Access module in generate statement via VPI

### ISSUE THREAD

**Issue by marph91** [tgingold/ghdl#450]
Hello,
I have a problem to get the correct module names from a generate statement when using cocotb + ghdl (see also [https://stackoverflow.com/questions/46988237/unusable-module-names-with-generate-statement-in-cocotb](url) ).

Using the attached example (modified from [http://ghdl.free.fr/site/uploads/Main/vpi-ex-ghdl.tar](url) ). The output from `vpiFullName` is as expected, but the output from `vpiName` is `(1)` instead of `gen_one(1)`. This seems to be the case for "for generate statements" as well as "if generate statements".

VPI example: [vpi-ex-ghdl.tar.gz](https://github.com/tgingold/ghdl/files/1428446/vpi-ex-ghdl.tar.gz)

**Comment by tgingold** [comment]
The vpiName issue is now fixed.  I am not yet sure the cocotb testcase would pass however.

**Comment by marph91** [comment]
Thank you for the fast fix. The "for generate statement" works now. However im still getting `B1` instead of `gen_if` for the "if generate statement" (last two output lines).

**Comment by tgingold** [comment]
> On 31 Oct 2017, at 14:59, marph91 <notifications@github.com> wrote:
> 
> Thank you for the fast fix. The "for generate statement" works now. However im still getting B1 instead of gen_if for the "if generate statement" (last two output lines).

You're right.  Now fixed (I hope).

Tristan.
